# Generated by Django 2.2.1 on 2019-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('pharmacy_name', models.CharField(max_length=300)),
                ('pharmacy_location', models.TextField()),
            ],
        ),
    ]
